tunnel: argyfx-tunnel
credentials-file: C:\Users\rmonaco\.cloudflared\9e0bf499-7221-46d5-a9b6-57c412d4e239.json

# Improved configuration for better stability
ingress:
  - hostname: argyfx.com
    path: /api/*
    service: http://127.0.0.1:5001
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      noTLSVerify: true
  - hostname: argyfx.com
    service: http://127.0.0.1:8501
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      noTLSVerify: true
  - service: http_status:404

# Global tunnel settings for better stability
retries: 5
grace-period: 30s
